import { Component } from "@angular/core";

@Component({
  selector: 'monitors',
  templateUrl: './monitor-list.component.html'
})
export class MonitorListComponent {
  monitors: any[] = [{
  "id": 1,
  "brand": "Dell",
  "model": "UltraSharp 32 Ultra HD 8K Monitor (UP3218K)",
  "image": "url",
  "info-link": "url",
  "street-price": 3900,
  "diagonal": 31.5,
  "resolution": "7680 x 4320",
  "contrast": "1300:1",
  "response": "6 ms (gray-to-gray)",
  "viewing-angle": 178,
  "brightness": 400,
  "color": "1.07 billion",
  "pixel-pitch": "",
  "io-ports": ["USB 3.0 downstream (Type A)", "USB 3.0 downstream (Type A (power only))", "USB 3.0 upstream (Type B)Audio line-out"],
  "card-reader": "",
  "position-adjustment": "Height 4.7 in, pivot (rotation) 90, swivel 60, tilt -5/+21, wall mount mount 100 x 100 mm",
  "look-up-table": "",
  "dual-view-mode": "",
  "video-ports": "2 x DisplayPort",
  "dimentions": "With stand - width: 28.4 in - depth: 8.5 in - height: 24.3 in, Without stand - width: 28.4 in - depth: 2.1 in - height: 16.6 inIPS",
  "release-date": "",
  "affiliate-link": "",
  "review-links": "",
  "panel-type": "IPS",
  "aspect-ratio": "Widescreen - 16:9",
  "refresh-rate": "60 Hz",
  "screen-coating": "Anti-reflective, 2H Hard Coating",
  "features": "100% Adobe RGB color gamut, 100% sRGB color gamut, 98% DCI-P3, 100% Rec 709 color gamut, Security lock slot, anti-theft protection",
  "power": "87 Watt, AC 120/230 V (50/60 Hz)",
  "warranty": "3-Years Advanced Exchange Service and Premium Panel Guarantee",
  "manufacturer-part": "095P9, Dell part 210-ALEZ"

  }, {
  "id": 2,
  "brand": "Sharp",
  "model": "UltraSharp 32 Ultra HD 8K Monitor (UP3218K)",
  "image": "url",
  "info-link": "url",
  "street-price": 3900,
  "diagonal": 31.5,
  "resolution": "7680 x 4320",
  "contrast": "1300:1",
  "response": "6 ms (gray-to-gray)",
  "viewing-angle": 178,
  "brightness": 400,
  "color": "1.07 billion",
  "pixel-pitch": "",
  "io-ports": ["USB 3.0 downstream (Type A)", "USB 3.0 downstream (Type A (power only))", "USB 3.0 upstream (Type B)Audio line-out"],
  "card-reader": "",
  "position-adjustment": "Height 4.7 in, pivot (rotation) 90, swivel 60, tilt -5/+21, wall mount mount 100 x 100 mm",
  "look-up-table": "",
  "dual-view-mode": "",
  "video-ports": "2 x DisplayPort",
  "dimentions": "With stand - width: 28.4 in - depth: 8.5 in - height: 24.3 in, Without stand - width: 28.4 in - depth: 2.1 in - height: 16.6 inIPS",
  "release-date": "",
  "affiliate-link": "",
  "review-links": "",
  "panel-type": "IPS",
  "aspect-ratio": "Widescreen - 16:9",
  "refresh-rate": "60 Hz",
  "screen-coating": "Anti-reflective, 2H Hard Coating",
  "features": "100% Adobe RGB color gamut, 100% sRGB color gamut, 98% DCI-P3, 100% Rec 709 color gamut, Security lock slot, anti-theft protection",
  "power": "87 Watt, AC 120/230 V (50/60 Hz)",
  "warranty": "3-Years Advanced Exchange Service and Premium Panel Guarantee",
  "manufacturer-part": "095P9, Dell part 210-ALEZ"

  }];
}
